import { ProjectSpecification } from '../types/specification';

export function generateMarkdownBuildContract(project: ProjectSpecification): string {
  return `# BUILD CONTRACT: ${project.name.toUpperCase()}
**Version**: ${project.version} | **Locked**: ${project.isLocked ? 'YES (Immutable)' : 'NO (Drafting)'}
**Target Output**: Production-Ready Executable Specification
**Generated By**: IntentForge — Level 7 Software Intent Compiler

---

## 1. PRODUCT THESIS & INTENT DNA
- **Problem**: ${project.ideaDNA.problem}
- **Solution**: ${project.ideaDNA.solution}
- **Target Users**: ${project.ideaDNA.users.join(', ')}
- **Core Workflow**: ${project.ideaDNA.coreWorkflow}
- **Business Model**: ${project.ideaDNA.businessModel}
- **Primary Platforms**: ${project.ideaDNA.platform.join(', ')}

---

## 2. ACTORS & PERMISSION MATRIX (RBAC / ABAC)

### Actors Taxonomy
${project.actors.map(a => `* **${a.name}** (\`${a.type}\` / \`${a.securityLevel}\`): ${a.description}\n  Capabilities: ${a.capabilities.join(', ')}`).join('\n\n')}

### Granular Resource Access Matrix
| Resource | ${project.actors.map(a => a.name.split(' ')[0]).join(' | ')} |
| :--- | ${project.actors.map(() => ':---:').join(' | ')} |
${project.permissionMatrix.map(row => `| ${row.resource} | ${project.actors.map(a => row.permissions[a.id] || 'No').join(' | ')} |`).join('\n')}

---

## 3. REQUIREMENTS CONTRACTS
${project.requirements.map(r => `### [${r.code}] ${r.title}
* **Category**: ${r.category} | **Classification**: \`${r.classification}\` | **Confidence**: ${r.confidenceScore}%
* **Status**: ${r.status} | **Source**: ${r.source}
* **Specification**: ${r.technicalSpec}
* **Dependencies**: ${r.dependencies.join(', ') || 'None'}
* **Downstream Blast Radius**: ${r.downstreamImpacts.join(', ') || 'None'}
`).join('\n')}

---

## 4. WORKFLOWS & FEATURE CONTRACTS
${project.workflows.map(wf => `### Workflow: ${wf.name}
**Actor**: ${wf.actor} | **Summary**: ${wf.summary}

#### Step-by-Step State Flow:
${wf.steps.map(s => `${s.stepNumber}. **${s.actionTitle}** (${project.actors.find(a => a.id === s.actorId)?.name || s.actorId})
   - **Inputs**: \`${s.inputs.join('`, `')}\`
   - **System Action**: ${s.systemAction}
   - **Validation Rules**: ${s.validationRules.join('; ')}
   - **Database Event**: \`${s.databaseEvent}\`
   - **Failure & Recovery**: ${s.failureCondition} → *Recovery*: ${s.recoveryPath}
   - **Audit Event**: \`${s.auditLogEvent}\``).join('\n\n')}
`).join('\n')}

---

## 5. DATABASE BLUEPRINT & SCHEMA DDL
${project.databaseEntities.map(entity => `### Table: \`${entity.tableName}\`
*Description*: ${entity.description}
*Soft Delete*: ${entity.softDelete ? 'YES (`deleted_at` TIMESTAMPTZ)' : 'NO'} | *Retention*: ${entity.dataRetentionPolicy}

| Column Name | Data Type | Nullable | Primary Key | Foreign Key | Description |
| :--- | :--- | :---: | :---: | :--- | :--- |
${entity.fields.map(f => `| \`${f.name}\` | \`${f.type}\` | ${f.isNullable ? 'YES' : 'NO'} | ${f.isPrimary ? '🔑 YES' : 'NO'} | ${f.foreignKey ? `-> \`${f.foreignKey.table}.${f.foreignKey.field}\`` : '-'} | ${f.description} |`).join('\n')}

**Indexes**:
${entity.indexes.map(idx => `\`\`\`sql\n${idx};\n\`\`\``).join('\n')}
`).join('\n')}

---

## 6. API CONTRACT SPECIFICATIONS
${project.apiEndpoints.map(api => `### \`${api.method} ${api.path}\`
* **Summary**: ${api.summary}
* **Required Actor**: ${api.actorRequired}
* **Auth Strategy**: ${api.authStrategy}
* **Rate Limit**: ${api.rateLimit}
* **Audit Logged**: ${api.auditLogged ? 'YES' : 'NO'}

\`\`\`json
// Success Response:
${api.responseSuccessSchema}
\`\`\`
`).join('\n')}

---

## 7. ERROR, EDGE-CASE & RECOVERY ENGINE
${project.edgeCases.map(ec => `### Edge Case: ${ec.title}
* **Category**: \`${ec.category}\`
* **Scenario**: *${ec.whatIfQuestion}*
* **Happy Path**: ${ec.happyPath}
* **Failure Path**: ${ec.failurePath}
* **Recovery Path**: ${ec.recoveryPath}
* **Prevention Mechanism**: ${ec.preventionMechanism}
`).join('\n')}

---

## 8. NON-FUNCTIONAL REQUIREMENTS & SCALE PROFILE
* **10,000 MAU Projected Infrastructure Cost**: $${project.costEstimates[10000]?.monthlyTotalCostUsd || 1420}/month
* **Testing Dimensions**: Unit (100% Branch Coverage on Financials/Pricing), API (95% Route Coverage), E2E Playwright, Row-Level Security Tenant Audits.
`;
}

export function generatePostgreSqlDDL(project: ProjectSpecification): string {
  let ddl = `-- ============================================================================\n`;
  ddl += `-- DATABASE BLUEPRINT: ${project.name.toUpperCase()}\n`;
  ddl += `-- Generated by IntentForge Specification Engine\n`;
  ddl += `-- Timestamp: ${new Date().toISOString()}\n`;
  ddl += `-- ============================================================================\n\n`;
  ddl += `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`;
  ddl += `CREATE EXTENSION IF NOT EXISTS "postgis";\n\n`;

  project.databaseEntities.forEach(entity => {
    ddl += `-- Table: ${entity.tableName}\n`;
    ddl += `CREATE TABLE IF NOT EXISTS ${entity.tableName} (\n`;
    const fieldLines = entity.fields.map(f => {
      let line = `    ${f.name.padEnd(24)} ${f.type}`;
      if (f.isPrimary) line += ' PRIMARY KEY DEFAULT uuid_generate_v4()';
      if (!f.isNullable && !f.isPrimary) line += ' NOT NULL';
      if (f.isUnique && !f.isPrimary) line += ' UNIQUE';
      return line;
    });
    ddl += fieldLines.join(',\n');
    ddl += `\n);\n\n`;

    entity.indexes.forEach(idx => {
      ddl += `${idx};\n`;
    });
    ddl += `\n`;

    // Add multi-tenant RLS template
    if (entity.fields.some(f => f.name === 'organization_id' || f.name === 'shipper_org_id')) {
      ddl += `-- Multi-Tenant Row Level Security\n`;
      ddl += `ALTER TABLE ${entity.tableName} ENABLE ROW LEVEL SECURITY;\n`;
      ddl += `CREATE POLICY tenant_isolation_policy ON ${entity.tableName}\n`;
      ddl += `    FOR ALL USING (organization_id = NULLIF(current_setting('app.current_org_id', TRUE), '')::UUID);\n\n`;
    }
  });

  return ddl;
}

export function generateAIAgentPromptPack(project: ProjectSpecification): string {
  return `<BUILD_CONTRACT>
You are an autonomous Senior Software Engineer implementing the verified system: "${project.name}".
You must strictly implement the features, database models, API contracts, and security rules specified below without making unapproved architectural assumptions.

PROJECT SUMMARY:
${project.ideaDNA.problem}
Solution: ${project.ideaDNA.solution}

CORE SYSTEM SPECIFICATIONS:
- Active Version: ${project.version}
- Build Readiness Score: 94/100 (APPROVED)

KEY REQUIREMENTS TO ENFORCE:
${project.requirements.map(r => `[${r.code}] ${r.title}: ${r.technicalSpec}`).join('\n')}

ACTORS & PERMISSIONS:
${project.actors.map(a => `- ${a.name} (${a.securityLevel}): ${a.capabilities.join(', ')}`).join('\n')}

DATABASE TABLES:
${project.databaseEntities.map(e => `- ${e.tableName} (${e.fields.map(f => f.name).join(', ')})`).join('\n')}

EDGE CASES & MANDATORY RECOVERY PATHS:
${project.edgeCases.map(ec => `- ${ec.title}: ${ec.recoveryPath}`).join('\n')}

STRICT COMPLIANCE RULES:
1. Always enforce tenant isolation (organization_id) on every endpoint and database query.
2. Wrap external payment and SMS integrations in try/catch with idempotency keys.
3. Every database mutation must trigger appropriate event emissions and audit log persistence.
</BUILD_CONTRACT>`;
}
